-- AlterTable
ALTER TABLE `users` MODIFY `role` ENUM('ADMIN', 'MANAGER', 'VIEWER') NOT NULL;

-- AlterTable
ALTER TABLE `audit_logs` MODIFY `action` ENUM('LOGIN', 'LOGOUT', 'DOWNLOAD', 'LIST', 'CREATE_USER', 'UPDATE_USER', 'DISABLE_USER', 'ENABLE_USER', 'DELETE_USER', 'PASSWORD_RESET', 'ADD_PERMISSION', 'REMOVE_PERMISSION') NOT NULL;
